jwt:
  expiration: 86400
  secret: 123456
  tokenHead: Bearer
  tokenHeader: Authorization
logging:
  config: classpath:logback.xml

server:
  port: 8080
  servlet:
    context-path: /ofs

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/ofs?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
  jpa:
    show-sql: false

  redis:
    cluster:
      nodes: 127.0.0.1:6379
    database: 0
    lettuce:
      pool:
        max-active: 10
        max-idle: 8
        max-wait: -1
        min-idle: 0
    password: 123456
    timeout: 5000
  web:
    resources:
      static-locations: classpath:/templates/
